/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include"FreeRTOSConfig.h"
#include"FreeRTOS.h"
#include"task.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vMainTaskFunction(void * pvParam)//parameter pass krava lagto
{
	while(1){
		// work
		led_toggle();
		vTaskDelay(1000/portTICK_RATE_MS);//1000 ms cha 1000 tiks medhe convert krnya sathi
	}
	vTaskDelete(NULL);//null=task id pass hogi arg ki
}



int main(void)
{
	led_init();

	xTaskCreate(vMainTaskFunction, "Aperiodic", configMINIMAL_STACK_SIZE, NULL, 4, NULL);//4 means(total 7 priority hai to 0 low hai and 6 high hai to unmese ek li 4)

	vTaskStartScheduler();//scheduler call hoto tenvha task create hoto
	while(1);//bar bar scheduler la call krnya sathi
}














