/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include "FreeRTOSConfig.h"
#include "FreeRTOS.h"
#include "task.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vtaskfunction1(void *param)
{
	while(1)
	{
		led_toggle(LED_RED);
		vTaskDelay(100/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

void vtaskfunction2(void *param)
{
	portTickType xLastWakeTime;
	while(1)
	{
		xLastWakeTime=xTaskGetTickCount();
		led_toggle(LED_GREEN);
		vTaskDelayUntil(&xLastWakeTime,1000/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

int main(void)
{

	led_init(LED_RED);
	led_init(LED_GREEN);
	xTaskCreate(vtaskfunction1,"apriodic",configMINIMAL_STACK_SIZE, NULL, 5 ,NULL);
	xTaskCreate(vtaskfunction2,"priodic",configMINIMAL_STACK_SIZE, NULL, 5 ,NULL);
	vTaskStartScheduler();
	while(1);
}
